# Generated by Django 5.2.3 on 2025-06-24 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Titre de l’histoire", max_length=100),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("animals", "Animaux"),
                            ("fantasy", "Fantastique"),
                            ("daly_hero", "Petit héros du quotidien"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Prompt utilisé pour générer l'histoire"
                    ),
                ),
                (
                    "generated_text",
                    models.TextField(help_text="Texte généré par le modèle"),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        help_text="Liste d'URLs ou chemins d'images",
                        null=True,
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le fichier audio généré",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
