# Generated by Django 5.2.3 on 2025-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rawina", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="audio_url",
        ),
        migrations.RemoveField(
            model_name="story",
            name="images",
        ),
        migrations.AddField(
            model_name="story",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier audio généré",
                null=True,
                upload_to="generated_audios/",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="generated_images/"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="theme",
            field=models.CharField(
                choices=[
                    ("animals", "Animals"),
                    ("fantasy", "Fantasy"),
                    ("daily_hero", "Daily Hero"),
                ],
                max_length=20,
            ),
        ),
    ]
