# Generated by Django 5.2.3 on 2025-07-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawina', '0003_remove_story_audio_file_remove_story_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='prompt',
        ),
        migrations.AlterField(
            model_name='story',
            name='generated_text',
            field=models.TextField(help_text='Texte généré automatiquement'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
