# Generated by Django 5.2.3 on 2025-07-16 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawina', '0004_remove_story_prompt_alter_story_generated_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='generated_text',
        ),
        migrations.AddField(
            model_name='story',
            name='generated_text_en',
            field=models.TextField(blank=True, help_text='Automatically generated text', null=True, verbose_name='Generated Text (English)'),
        ),
        migrations.AddField(
            model_name='story',
            name='generated_text_fr',
            field=models.TextField(blank=True, help_text='Automatically generated text', null=True, verbose_name='Generated Text (French)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='story',
            name='theme',
            field=models.CharField(choices=[('animals', 'Animals'), ('fantasy', 'Fantasy'), ('daily_hero', 'Daily Hero')], max_length=20, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
