# Generated by Django 5.2.3 on 2025-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawina', '0005_remove_story_generated_text_story_generated_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='story',
            name='title_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
