from django.db import models
from django.contrib.auth.models import User


class Story(models.Model):
    THEME_CHOICES = [
        ('animals', 'Animals'),
        ('fantasy', 'Fantasy'),
        ('daily_hero', 'Daily Hero'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='stories')
    title = models.CharField(max_length=100, help_text="Story Title")
    theme = models.CharField(max_length=20, choices=THEME_CHOICES)
    prompt = models.TextField(help_text="Prompt used to generate the story")
    generated_text = models.TextField(help_text="Text generated by the model")

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} – {self.user.username} ({self.created_at.date()})"
